#端口信息
server:
  port: 8080
#spring配置
spring:
  application:
    name: gateway #微服务名称(用于nacos微服务注册)
  cloud:
    nacos:
      server-addr: 192.168.92.129:8848  #微服务nacos地址
    #路由过滤
    gateway:
      #1.路由过滤
      routes:
        #第一个微服务
        - id: item-service # 路由规则id，自定义，唯一
          uri: lb://item-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/items/**,/search/** # 这里是以请求路径作为判断规则
        #第二个微服务
        - id: cart-servic
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        #第三个微服务
        - id: user-servic
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**
        #第四个微服务
        - id: trade-servic
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        #第五个微服务
        - id: pay-servic
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
#log日志
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"