server:
  port: 8084
feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持
hm:
  swagger:
    title: "购物车用户接口文档"
    package: com.hmall.user.controller
  db:
    database: hm-user
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090  # sentinel控制台地址
      # 因为restful风格，如果不设置的话同一个controller下的接口都是一个资源
      http-method-specify: true #是否设置请求方式作为资源名称
